#ifndef SAMPLER_H
#define SAMPLER_H

class PointD2;

/*!
 * \brief Base class for samplers that generate 2D point samples in a
 *        uniform square.
 */
class Sampler
{
public:
    explicit Sampler(unsigned short num_samples);

    /*!
     * \brief Get the next sample point.
     * Starts with the first sample again if num_samples have been returned.
     */
    const PointD2 &next() const = 0;
    /*!
     * \brief Number of sample points generated by this sampler.
     */
    unsigned short num_samples() const;

protected:
    unsigned short _num_samples;
};

#endif // SAMPLER_H
